#!/usr/bin/env python3
"""
Scheme Authority dev-PKI bootstrap script.

Generates the **scheme-level** certificate hierarchy — the shared trust
infrastructure that every PISP in this scheme will be validated against.
This script knows nothing about individual PISPs.

Usage
-----
    python3 pki/setup_dev_pki.py

Outputs (relative to repo root)
--------------------------------
    pki/generated/
        root-ca.cert.pem         ← committed to git (public trust anchor)
        root-ca.key.pem          ← gitignored  (air-gapped after this run)
        intermediate-ca.cert.pem ← committed to git (online CA cert)
        intermediate-ca.key.pem  ← gitignored  (SA container only)

Key-hygiene model
-----------------
Layer             Held by at runtime      Committed to git
Root CA key       Nobody (offline)        No
Root CA cert      All PISPs + SA          Yes
Intermediate key  SA container only       No
Intermediate cert All PISPs + SA          Yes
PISP CA key       Issuing PISP (volume)   No — generated by PISP at first boot
PISP CA cert      SA DB + PISP volume     No — issued by SA at registration

PISP first-boot flow
--------------------
Each PISP container is self-sovereign.  On first boot it:
  1. Generates its own CA key pair and writes it to its named volume.
  2. Builds a CSR and POSTs it to the Scheme Authority (POST /scheme/pisps).
  3. The SA signs the CSR with the Intermediate CA and returns the cert.
  4. The PISP writes the cert to its named volume and proceeds normally.

This script is re-run whenever the scheme CA needs to be rotated.
Adding or removing PISPs never requires touching this script.
"""

from __future__ import annotations

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Bootstrap the Python path so we can import pki.py from the repo root.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).parent.parent.resolve()
PKI_DIR = REPO_ROOT / "pki"

sys.path.insert(0, str(PKI_DIR))
import pki as _pki


def _write_cert(path: Path, cert) -> None:
    from cryptography.hazmat.primitives import serialization
    path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    print(f"  cert → {path.relative_to(REPO_ROOT)}")


def _write_key(path: Path, key) -> None:
    from cryptography.hazmat.primitives import serialization
    path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    path.chmod(0o600)   # owner-readable only
    print(f"  key  → {path.relative_to(REPO_ROOT)}  (gitignored, mode 600)")


def main() -> None:
    out = REPO_ROOT / "pki" / "generated"
    out.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Step 1: Scheme Root CA  (key stays offline after this script runs)
    # ------------------------------------------------------------------
    print("\n[1/2] Generating Scheme Root CA …")
    root_key, root_cert = _pki.generate_root_ca()
    _write_key(out / "root-ca.key.pem", root_key)
    _write_cert(out / "root-ca.cert.pem", root_cert)

    # ------------------------------------------------------------------
    # Step 2: Scheme Intermediate CA  (key lives in SA container only)
    # ------------------------------------------------------------------
    print("\n[2/2] Generating Scheme Intermediate CA …")
    int_key, int_cert = _pki.generate_intermediate_ca(root_key, root_cert)
    _write_key(out / "intermediate-ca.key.pem", int_key)
    _write_cert(out / "intermediate-ca.cert.pem", int_cert)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print("\n✅ Scheme CA generation complete.")
    print("\nGitignored (private keys — never commit these):")
    for p in sorted(out.rglob("*.key.pem")):
        print(f"    {p.relative_to(REPO_ROOT)}")
    print("\nCommit-safe (public certs — share with all PISPs):")
    for p in sorted(out.rglob("*.cert.pem")):
        if p.exists():
            print(f"    {p.relative_to(REPO_ROOT)}")
    print()
    print("Next step: docker compose up")
    print("  PISPs generate their own keys and register with the SA on first boot.")
    print()


if __name__ == "__main__":
    main()
